controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use yii\web\Session;
use app\models\LoginForm;
use app\models\Datum;

//use app\models\UserRole;
//use app\models\UserClient;
//use app\models\MClient;
use yii\helpers\ArrayHelper;
use yii\db\Query;
class SiteController extends Controller
{

    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

	

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }
	
    private function controlview($data){
		if($data == 0){
			return $this->redirect(['login']);
		}else if($data == 1){
			return $this->redirect(['akses']);
		}else if($data == 2){
			return $this->redirect(['dashboard']);
		}else{
			throw new \yii\web\NotFoundHttpException("Sorry page not found.");
		}
	}
	public function actionDatainput(){
		$tanggal =  date("Y/m/d");
		$datafilter=null;
		$bln = "";
		$thn = "";
		$modeldata = new Datum();
		
		if(Yii::$app->request->post("btnfilter")){
				$model = Datum::find()->all();
				$bln = Yii::$app->request->post("bln");
				$thn = Yii::$app->request->post("thn");
				$blnget = strtotime($bln);
				
				$thnget = strtotime($thn);
				$year = date('Y',$thnget);
				$month = date('m',$blnget);
	
				
				$query = new Query;
				$query->select([
						'*',
						])  
						->from('datum')
						->where(['tahun'=>$year,'bulan'=>$month])->all();
				$command = $query->createCommand();
				$datafilter = $command->queryAll();
		}else if(Yii::$app->request->post("btnproses")){
			
		
		}else if ($modeldata->load(Yii::$app->request->post()) && $modeldata->save()) {
			return $this->redirect(['datainput']);
		}
		return $this->render('datainput_v', [
			'tanggal'=>$tanggal,
			'bln'=>$bln,
			'thn'=>$thn,
			'modeldata'=>$modeldata,
			'model'=>$datafilter,
			'title' => "SISTEM PENGAMBILAN KEPUTUSAN",
		]);	
	
	}
    public function actionIndex()
    {
		$data = Yii::$app->sess->checksession();
		$this->controlview($data);
	}

    
     public function actionLogin()
    {	
        $data = Yii::$app->sess->checksession();
		if($data == 1){//1
			return $this->redirect(['akses']);
		}else if($data == 2){
			return $this->redirect(['dashboard']);
		}else if($data == 0){
			$this->layout = 'themelogin';
			$model = new LoginForm();
			if (Yii::$app->request->post()) {
				$username = Yii::$app->request->post('LoginForm')['username'];
				$password = Yii::$app->request->post('LoginForm')['password'];
				
				$userdata =  Yii::$app->db->createCommand("SELECT * FROM akses WHERE username='".$username."' AND password='".$password."'")->queryAll();
			
				if($userdata != "" && $userdata!= null){
					Yii::$app->sess->regissess($userdata);
					return $this->redirect(['dashboard']);
				}else{
					Yii::$app->session->setFlash('error', "Username atau Password salah");
					return $this->redirect(['login']);
				}
			}else{
				return $this->render('login', [
					'model' => $model,
				]);
			}
		}else{
			throw new \yii\web\NotFoundHttpException("Sorry page not found.");
		}
	}
     
	public function actionAkses(){
		$data = Yii::$app->sess->checksession();
		if($data == 0){
			return $this->redirect(['login']);
		}else if($data == 2){
			return $this->redirect(['dashboard']);
		}else if($data == 1){
			$userdata = Yii::$app->sess->checkgetsess("userdata");
			$this->layout = 'themelogin';
			foreach($userdata as $data){
				$Kode_Karyawan=$data["Kode_Karyawan"];
				$Nama_Karyawan=$data["Nama_Karyawan"];
				}
			$userclient = Userclient::find()->where(['id_user'=>$Kode_Karyawan,'aktif'=>'Y'])->all();
			$client_aktif = array();foreach($userclient as $row){$client_aktif[]=$row->id_client;}
			$client = MClient::find()->where(['id_client'=>$client_aktif])->all();$listclient=ArrayHelper::map($client,'id_client','client');
			
			if (Yii::$app->request->post('client') != null && Yii::$app->request->post('role') !=null) {
				$client = Yii::$app->request->post('client');
				$role = Yii::$app->request->post('role');
				Yii::$app->sess->regiswithname('client',$client);
				Yii::$app->sess->regiswithname('role',$role);
				
				$dataclient = Yii::$app->sess->checkgetsess('client');
				$datarole = Yii::$app->sess->checkgetsess('role');
				
				$query = new Query;
                    $query->select([
                            'c.*',
                            'a.id_user_client',
                            'a.id_user_role'
                            ])  
                            ->from('akses AS a')
                            ->Join(	'INNER JOIN', 
                                'akses_det AS b',
                                'a.id_akses = b.id_akses'
                            )->Join('INNER JOIN', 
                            'm_modul AS c',
                            'b.id_modul = c.id_modul'
                             )->where(['a.id_user_client'=>$dataclient,'a.id_user_role'=>$datarole]
                            );
				$command = $query->createCommand();
				$menu = $command->queryAll();
				if($menu == null || $menu == ""){
					Yii::$app->sess->regiswithname('menu',null);
					Yii::$app->sess->regiswithname('submenu',null);
					Yii::$app->sess->regiswithname('subsubmenu',null);
				}else{
					
					Yii::$app->sess->regiswithname('menu',$menu);
					$datamenu = $menu;
						foreach($menu as $datamenu){
						$paramIdModul[] = $datamenu['id_modul'];
					}
					$query = new Query;
                    $query->select([
                        'b.id_modul_det',
                        'b.id_modul',
                        'b.modul',
                        'b.link',
                        'b.id_modul',
                        'b.parent'
                        ])  
					->from('m_modul AS a')
					->Join(	'RIGHT JOIN', 
						'm_modul_det AS b',
						'a.id_modul = b.id_modul'
					)->where(['b.aktif'=>'1']
					)->andWhere(['IN','b.id_modul',$paramIdModul]);
					$command = $query->createCommand();
					$submenu = $command->queryAll();
					if($submenu == null || $submenu == ""){
                            Yii::$app->sess->regiswithname('submenu',null);
							Yii::$app->sess->regiswithname('subsubmenu',null);
					}else{
						Yii::$app->sess->regiswithname('submenu',$submenu);
						foreach($submenu as $datasubmenu){
							$id_modul_det[] = $datasubmenu['id_modul_det'];
						}
						$query = new Query;
						$query->select([
							'b.id_modul_det',
							'b.modul',
							'b.link',
							])  
							->from('m_modul_det AS a')
							->Join(	'LEFT JOIN', 
								'm_modul_det_det AS b',
								'a.id_modul_det = b.id_modul_det'
							)->where(['b.aktif'=>'1','a.aktif'=>'1']
							)->andWhere(['IN','b.id_modul_det',$id_modul_det]);
							$command = $query->createCommand();
							$subsubmenu = $command->queryAll();
							if($subsubmenu == null || $subsubmenu == ""){
								Yii::$app->sess->regiswithname('subsubmenu',null);
							}else{
								Yii::$app->sess->regiswithname('subsubmenu',$subsubmenu);
							}			   
					}
				}
				return $this->redirect(['dashboard']);
			}else{
				return $this->render('akses',[
					 'listclient' => $listclient,
					 'userdata'=>$Nama_Karyawan
				]);		
			}
		}else{
			throw new \yii\web\NotFoundHttpException("Sorry page not found.");
		}
	}

     public function actionLogout()
    {
        $session = Yii::$app->session;
        $session->open();
        if(Yii::$app->request->post()){
            if($session->get('userdata') != null){
                $session->destroy();
                return $this->redirect(['login']);
            }else{
                throw new \yii\web\NotFoundHttpException("Sorry page not found.");
            }
        }else{
            throw new \yii\web\NotFoundHttpException("Sorry page not found.");
        }
    }

	public function actionDashboard(){
		$userdata = Yii::$app->sess->checkgetsess("userdata");
		$data = Yii::$app->sess->checksession();
		if($data == 1){
			return $this->redirect(['akses']);
		}else if($data == 0){
			return $this->redirect(['login']);
		}
		
		return $this->render('index',[
			'userdata'=>$userdata 
		]);

	}

 public function  actionProsesfuzzy(){
	print_r("daat");
}
}

views/layouts/main.php
<?php
use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use yii\helpers\Url;
use yii\web\Session;

$session = Yii::$app->session;
$userdata = $session->get('userdata');
foreach($userdata as $data){
	$Kode_Karyawan=$data["id"];
	$Nama_Karyawan=$data["username"];
}
AppAsset::register($this);
                
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
	<meta charset="<?= Yii::$app->charset ?>">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<?= Html::csrfMetaTags() ?>
	<title><?= Html::encode($this->title) ?></title>
	<?php $this->head() ?>
</head>
<body class="hold-transition skin-blue sidebar-mini">
<?php $this->beginBody() ?>
<div class="wrapper">

  <header class="main-header">
    <!-- Logo -->
    <a href="<?= Url::base().'/site/dashboard';?>" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>S</b>PK</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg">SISTEM SPK</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <span class="hidden-xs"> <?=$Nama_Karyawan?></span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <!--img src="theme/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image"-->

                <p>
                  <?=$Nama_Karyawan?>
                  
                </p>
              </li>
              <li class="user-footer">
                <div class="pull-right">
				<a href="<?= Url::base().'/site/logout';?>" class="btn btn-default btn-flat" data-method="post"> Sign out</a>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
  </header>

  <aside class="main-sidebar">
    <section class="sidebar">
      <ul class="sidebar-menu" data-widget="tree">
      <li><a href="<?= Url::base().'/site/datainput';?>"> <span>Data Input</span></a></li>
      <li><a href="<?= Url::base().'/site/fuzzylogic';?>"> <span>Fuzzy Logic</span></a></li>
      <li><a href="<?= Url::base().'/site/profilematching';?>"> <span>Profile Matching</span></a></li>
      <li><a href="<?= Url::base().'/site/nilairangking';?>"> <span>Nilai Ranking</span></a></li>
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>
 <div class="content-wrapper">
 <?= 
   Breadcrumbs::widget([
      'homeLink' => [ 
                      'label' => Yii::t('yii', 'Dashboard'),
                      'url' => Url::base().'/site/dashboard',
                 ],
      'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
   ]) 
?>
 
    <section class="content">
      <?= $content ?>
    </section>
    <!-- /.content -->
  </div>
  <footer class="main-footer">
    <strong>Copyright &copy; 2019 <a href="http://10.10.20.231/sirup/">PT. Sinar Roda Utama</a>.</strong> All rights
    reserved.
  </footer>

</div>
<!-- ./wrapper -->
<?php $this->endBody() ?>
<script>
  $(function () {
    var donut = new Morris.Donut({
    element  : 'sales-chart',
    resize   : true,
    colors   : ['#3c8dbc', '#f56954', '#00a65a'],
    data     : [
      { label: 'Nilai Total', value: 12 },
      { label: 'Kode', value: 30 },
      { label: 'Ranking', value: 20 }
    ],
    hideHover: 'auto'
  });
  $('#calendar').datepicker();
  var area = new Morris.Area({
    element   : 'revenue-chart',
    resize    : true,
    data      : [
      { y: '2011 Q1', item1: 2666, item2: 2666 },
      { y: '2011 Q2', item1: 2778, item2: 2294 },
      { y: '2011 Q3', item1: 4912, item2: 1969 },
      { y: '2011 Q4', item1: 3767, item2: 3597 },
      { y: '2012 Q1', item1: 6810, item2: 1914 },
      { y: '2012 Q2', item1: 5670, item2: 4293 },
      { y: '2012 Q3', item1: 4820, item2: 3795 },
      { y: '2012 Q4', item1: 15073, item2: 5967 },
      { y: '2013 Q1', item1: 10687, item2: 4460 },
      { y: '2013 Q2', item1: 8432, item2: 5713 }
    ],
    xkey      : 'y',
    ykeys     : ['item1', 'item2'],
    labels    : ['Item 1', 'Item 2'],
    lineColors: ['#a0d0e0', '#3c8dbc'],
    hideHover : 'auto'
  });
  var line = new Morris.Line({
    element          : 'line-chart',
    resize           : true,
    data             : [
      { y: '2011 Q1', item1: 2666 },
      { y: '2011 Q2', item1: 2778 },
      { y: '2011 Q3', item1: 4912 },
      { y: '2011 Q4', item1: 3767 },
      { y: '2012 Q1', item1: 6810 },
      { y: '2012 Q2', item1: 5670 },
      { y: '2012 Q3', item1: 4820 },
      { y: '2012 Q4', item1: 15073 },
      { y: '2013 Q1', item1: 10687 },
      { y: '2013 Q2', item1: 8432 }
    ],
    xkey             : 'y',
    ykeys            : ['item1'],
    labels           : ['Item 1'],
    lineColors       : ['#efefef'],
    lineWidth        : 2,
    hideHover        : 'auto',
    gridTextColor    : '#fff',
    gridStrokeWidth  : 0.4,
    pointSize        : 4,
    pointStrokeColors: ['#efefef'],
    gridLineColor    : '#efefef',
    gridTextFamily   : 'Open Sans',
    gridTextSize     : 10
  });

  $('.box ul.nav a').on('shown.bs.tab', function () {
    area.redraw();
    donut.redraw();
    line.redraw();
  });



    
	  $('#example1').DataTable({
      "scrollY": 250
    });
    $('#example2').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
    })
	  
	  
	  
    //Initialize Select2 Elements
    $('.select2').select2()

    //Datemask dd/mm/yyyy
  /*  $("#test2").inputmask("y", {
    alias: "date",    
    placeholder: "yyyy",
    yearrange: { minyear: 1900, maxyear: (new Date()).getFullYear() }});
*/
    $('#datemask').inputmask('y', { 
    alias: "date",    
    placeholder: "yyyy",
    yearrange: { minyear: 1900, maxyear: (new Date()).getFullYear() }});
    $('#datemaskbln').inputmask('m', { 
    alias: "date",    
    placeholder: "m"});
    
    //$('#datemask').inputmask('dd/mm/yyyy', { 'placeholder': 'dd/mm/yyyy' })
    //Datemask2 mm/dd/yyyy
    $('#datemask2').inputmask('mm/dd/yyyy', { 'placeholder': 'mm/dd/yyyy' })
    //Money Euro
    $('[data-mask]').inputmask()

    //Date range picker
    $('#reservation').daterangepicker()
    //Date range picker with time picker
    $('#reservationtime').daterangepicker({ timePicker: true, timePickerIncrement: 30, locale: { format: 'MM/DD/YYYY hh:mm A' }})
    //Date range as a button
    $('#daterange-btn').daterangepicker(
      {
        ranges   : {
          'Today'       : [moment(), moment()],
          'Yesterday'   : [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
          'Last 7 Days' : [moment().subtract(6, 'days'), moment()],
          'Last 30 Days': [moment().subtract(29, 'days'), moment()],
          'This Month'  : [moment().startOf('month'), moment().endOf('month')],
          'Last Month'  : [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
        },
        startDate: moment().subtract(29, 'days'),
        endDate  : moment()
      },
      function (start, end) {
        $('#daterange-btn span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'))
      }
    )


    //iCheck for checkbox and radio inputs
    $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
      checkboxClass: 'icheckbox_minimal-blue',
      radioClass   : 'iradio_minimal-blue'
    })
    //Red color scheme for iCheck
    $('input[type="checkbox"].minimal-red, input[type="radio"].minimal-red').iCheck({
      checkboxClass: 'icheckbox_minimal-red',
      radioClass   : 'iradio_minimal-red'
    })
    //Flat red color scheme for iCheck
    $('input[type="checkbox"].flat-red, input[type="radio"].flat-red').iCheck({
      checkboxClass: 'icheckbox_flat-green',
      radioClass   : 'iradio_flat-green'
    })

    //Colorpicker
    $('.my-colorpicker1').colorpicker()
    //color picker with addon
    $('.my-colorpicker2').colorpicker()

    //Timepicker
    $('.timepicker').timepicker({
      showInputs: false
    })
  })
</script>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/themeadvinput.php
<?php
use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset_datatableadv;
use yii\helpers\Url;
use yii\web\Session;

$session = Yii::$app->session;
/*$userdata = $session->get('userdata');
foreach($userdata as $data){
	$Kode_Karyawan=$data["Kode_Karyawan"];
	$Nama_Karyawan=$data["Nama_Karyawan"];
	$nik=$data["nik"];
}*/
AppAsset_datatableadv::register($this);
                
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
	<meta charset="<?= Yii::$app->charset ?>">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<?= Html::csrfMetaTags() ?>
	<title><?= Html::encode($this->title) ?></title>
	<?php $this->head() ?>
</head>
<body class="hold-transition skin-blue sidebar-mini">
<?php $this->beginBody() ?>
<div class="wrapper">

  <header class="main-header">
    <!-- Logo -->
    <a href="index2.html" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>S</b>RU</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg">SINAR RODA UTAMA</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <span class="hidden-xs"> <?php#$Nama_Karyawan?></span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <!--img src="theme/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image"-->

                <p>
                  <?php#$Nama_Karyawan?>
                  <small><?php#$nik?></small>
                </p>
              </li>
              <li class="user-footer">
			  <div class="pull-left">
                  <a href="http://10.10.20.231/sirup/masterkaryawan/update/<?php# $Kode_Karyawan;?>" class="btn btn-default btn-flat">Profile</a>
                </div>
                <div class="pull-right">
				<a href="<?= Url::base().'/site/logout';?>" class="btn btn-default btn-flat" data-method="post"> Sign out</a>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
  </header>

  <aside class="main-sidebar">
    <section class="sidebar">
      <ul class="sidebar-menu" data-widget="tree">
		<li class="header">MAIN NAVIGATION</li>
		<?php
			
			if($session->get('menu') != null){
				$menu = $session->get('menu');
				for($i=0;$i<sizeof($menu);$i++){
					 if($menu[$i]['parent'] == 1){
		?>
				<li class="treeview">
					<a href="#">
						<i class="<?=$menu[$i]['icon']?>"></i> <span><?=$menu[$i]['modul']?></span>
						<span class="pull-right-container">
						<i class="fa fa-angle-left pull-right"></i>
						</span>
					</a>
					<ul class="treeview-menu">
						<?php
						$submenu = $session->get('submenu');
							foreach($submenu as $smenu){
								if($smenu['id_modul'] == $menu[$i]['id_modul']){
									if($smenu['parent'] == '0'){
									?>
									<li>
										<a href="<?= Url::base().'/'.$smenu['link'];?>"><?= $smenu['modul'];?></a>
									</li>
									<?php	
									}else if($smenu['parent'] == '1'){
										
									?>
										 <li class="treeview">
										  <a href="#">
											<span><?= $smenu['modul'];?></span>
											<span class="pull-right-container">
											  <i class="fa fa-angle-left pull-right"></i>
											</span>
										  </a>
										  <ul class="treeview-menu">
										  <?php
										  $subsubmenu = $session->get('subsubmenu');
											for($j=0;$j<sizeof($subsubmenu);$j++){
												?>
												<li><a href="<?=$subsubmenu[$j]["link"];?>"><?=$subsubmenu[$j]["modul"];?></a></li>
												<?php
											
											}
										  ?>
										  
										  
											
										  </ul>
										</li>
									<?php	
									}
								}
							}
						?>
					
					</ul>
				</li>
		<?php
					 }else if($menu[$i]['parent'] == 0){
					?>
						<li>
							<a href="<?=$menu[$i]['link']?>"><i class="<?=$menu[$i]['icon']?>"></i> <?=$menu[$i]['modul']?></a>
						</li>
					<?php		 
					 }
				}
			}
			if($session['role'] == "1"){
		?>
			
			<li>
				<a href="<?php echo Url::base(); ?>/gii"><i class="fa fa-share-square-o"></i> Gii Tools</a>
			</li>
		<?php  
			}
		?>
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>
 <div class="content-wrapper">
 <section class="content-header">
 <?= 
   Breadcrumbs::widget([
      'homeLink' => [ 
                      'label' => Yii::t('yii', 'Dashboard'),
                      'url' => Url::base().'/site/dashboard',
                 ],
      'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
   ]) 
?>
 </section>

    <section class="content">
      <?= $content ?>
    </section>
    <!-- /.content -->
  </div>
  <footer class="main-footer">
    <strong>Copyright &copy; 2019 <a href="http://10.10.20.231/sirup/">PT. Sinar Roda Utama</a>.</strong> All rights
    reserved.
  </footer>

</div>
<!-- ./wrapper -->
<?php $this->endBody() ?>
<script>
  $(function () {
	  $('#example1').DataTable({
      "scrollY": 250
    });
    $('#example2').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
    })
	  
	  
	  
    //Initialize Select2 Elements
    $('.select2').select2()

    //Datemask dd/mm/yyyy
  /*  $("#test2").inputmask("y", {
    alias: "date",    
    placeholder: "yyyy",
    yearrange: { minyear: 1900, maxyear: (new Date()).getFullYear() }});
*/
    $('#datemask').inputmask('y', { 
    alias: "date",    
    placeholder: "yyyy",
    yearrange: { minyear: 1900, maxyear: (new Date()).getFullYear() }});
    $('#datemaskbln').inputmask('m', { 
    alias: "date",    
    placeholder: "m"});
    
    //$('#datemask').inputmask('dd/mm/yyyy', { 'placeholder': 'dd/mm/yyyy' })
    //Datemask2 mm/dd/yyyy
    $('#datemask2').inputmask('mm/dd/yyyy', { 'placeholder': 'mm/dd/yyyy' })
    //Money Euro
    $('[data-mask]').inputmask()

    //Date range picker
    $('#reservation').daterangepicker()
    //Date range picker with time picker
    $('#reservationtime').daterangepicker({ timePicker: true, timePickerIncrement: 30, locale: { format: 'MM/DD/YYYY hh:mm A' }})
    //Date range as a button
    $('#daterange-btn').daterangepicker(
      {
        ranges   : {
          'Today'       : [moment(), moment()],
          'Yesterday'   : [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
          'Last 7 Days' : [moment().subtract(6, 'days'), moment()],
          'Last 30 Days': [moment().subtract(29, 'days'), moment()],
          'This Month'  : [moment().startOf('month'), moment().endOf('month')],
          'Last Month'  : [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
        },
        startDate: moment().subtract(29, 'days'),
        endDate  : moment()
      },
      function (start, end) {
        $('#daterange-btn span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'))
      }
    )

    //Date picker
    $('#datepicker').datepicker({
      autoclose: true
    })

    //iCheck for checkbox and radio inputs
    $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
      checkboxClass: 'icheckbox_minimal-blue',
      radioClass   : 'iradio_minimal-blue'
    })
    //Red color scheme for iCheck
    $('input[type="checkbox"].minimal-red, input[type="radio"].minimal-red').iCheck({
      checkboxClass: 'icheckbox_minimal-red',
      radioClass   : 'iradio_minimal-red'
    })
    //Flat red color scheme for iCheck
    $('input[type="checkbox"].flat-red, input[type="radio"].flat-red').iCheck({
      checkboxClass: 'icheckbox_flat-green',
      radioClass   : 'iradio_flat-green'
    })

    //Colorpicker
    $('.my-colorpicker1').colorpicker()
    //color picker with addon
    $('.my-colorpicker2').colorpicker()

    //Timepicker
    $('.timepicker').timepicker({
      showInputs: false
    })
  })
</script>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/themelogin.php
<?php
use yii\helpers\Html;
use app\assets\AppAsset_login;
AppAsset_login::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
	<meta charset="<?= Yii::$app->charset ?>">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<?= Html::csrfMetaTags() ?>
	<title><?= Html::encode($this->title) ?></title>
	<?php $this->head() ?>
</head>
<body class="hold-transition login-page">
<?php $this->beginBody() ?>
<?= $content ?>
<?php $this->endBody() ?>

</body>
</html>
<?php $this->endPage() ?>