controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use yii\web\Session;
use app\models\LoginForm;
use app\models\Datum;

//use app\models\UserRole;
//use app\models\UserClient;
//use app\models\MClient;
use yii\helpers\ArrayHelper;
use yii\db\Query;
class SiteController extends Controller
{

    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

	

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }
	
    private function controlview($data){
		if($data == 0){
			return $this->redirect(['login']);
		}else if($data == 1){
			return $this->redirect(['akses']);
		}else if($data == 2){
			return $this->redirect(['dashboard']);
		}else{
			throw new \yii\web\NotFoundHttpException("Sorry page not found.");
		}
	}
	public function actionDatainput(){
		$tanggal =  date("Y/m/d");
		$datafilter=null;
		$bln = "";
		$thn = "";
		$modeldata = new Datum();
		
		if(Yii::$app->request->post("btnfilter")){
				$model = Datum::find()->all();
				$bln = Yii::$app->request->post("bln");
				$thn = Yii::$app->request->post("thn");
				$blnget = strtotime($bln);
				
				$thnget = strtotime($thn);
				$year = date('Y',$thnget);
				$month = date('m',$blnget);
	
				
				$query = new Query;
				$query->select([
						'*',
						])  
						->from('datum')
						->where(['tahun'=>$year,'bulan'=>$month])->all();
				$command = $query->createCommand();
				$datafilter = $command->queryAll();
		}else if(Yii::$app->request->post("btnproses")){
			
		
		}else if ($modeldata->load(Yii::$app->request->post()) && $modeldata->save()) {
			return $this->redirect(['datainput']);
		}
		return $this->render('datainput_v', [
			'tanggal'=>$tanggal,
			'bln'=>$bln,
			'thn'=>$thn,
			'modeldata'=>$modeldata,
			'model'=>$datafilter,
			'title' => "SISTEM PENGAMBILAN KEPUTUSAN",
		]);	
	
	}
    public function actionIndex()
    {
		$data = Yii::$app->sess->checksession();
		$this->controlview($data);
	}

    
     public function actionLogin()
    {	
        $data = Yii::$app->sess->checksession();
		if($data == 1){//1
			return $this->redirect(['akses']);
		}else if($data == 2){
			return $this->redirect(['dashboard']);
		}else if($data == 0){
			$this->layout = 'themelogin';
			$model = new LoginForm();
			if (Yii::$app->request->post()) {
				$username = Yii::$app->request->post('LoginForm')['username'];
				$password = Yii::$app->request->post('LoginForm')['password'];
				
				$userdata =  Yii::$app->db->createCommand("SELECT * FROM akses WHERE username='".$username."' AND password='".$password."'")->queryAll();
			
				if($userdata != "" && $userdata!= null){
					Yii::$app->sess->regissess($userdata);
					return $this->redirect(['dashboard']);
				}else{
					Yii::$app->session->setFlash('error', "Username atau Password salah");
					return $this->redirect(['login']);
				}
			}else{
				return $this->render('login', [
					'model' => $model,
				]);
			}
		}else{
			throw new \yii\web\NotFoundHttpException("Sorry page not found.");
		}
	}
     
	public function actionAkses(){
		$data = Yii::$app->sess->checksession();
		if($data == 0){
			return $this->redirect(['login']);
		}else if($data == 2){
			return $this->redirect(['dashboard']);
		}else if($data == 1){
			$userdata = Yii::$app->sess->checkgetsess("userdata");
			$this->layout = 'themelogin';
			foreach($userdata as $data){
				$Kode_Karyawan=$data["Kode_Karyawan"];
				$Nama_Karyawan=$data["Nama_Karyawan"];
				}
			$userclient = Userclient::find()->where(['id_user'=>$Kode_Karyawan,'aktif'=>'Y'])->all();
			$client_aktif = array();foreach($userclient as $row){$client_aktif[]=$row->id_client;}
			$client = MClient::find()->where(['id_client'=>$client_aktif])->all();$listclient=ArrayHelper::map($client,'id_client','client');
			
			if (Yii::$app->request->post('client') != null && Yii::$app->request->post('role') !=null) {
				$client = Yii::$app->request->post('client');
				$role = Yii::$app->request->post('role');
				Yii::$app->sess->regiswithname('client',$client);
				Yii::$app->sess->regiswithname('role',$role);
				
				$dataclient = Yii::$app->sess->checkgetsess('client');
				$datarole = Yii::$app->sess->checkgetsess('role');
				
				$query = new Query;
                    $query->select([
                            'c.*',
                            'a.id_user_client',
                            'a.id_user_role'
                            ])  
                            ->from('akses AS a')
                            ->Join(	'INNER JOIN', 
                                'akses_det AS b',
                                'a.id_akses = b.id_akses'
                            )->Join('INNER JOIN', 
                            'm_modul AS c',
                            'b.id_modul = c.id_modul'
                             )->where(['a.id_user_client'=>$dataclient,'a.id_user_role'=>$datarole]
                            );
				$command = $query->createCommand();
				$menu = $command->queryAll();
				if($menu == null || $menu == ""){
					Yii::$app->sess->regiswithname('menu',null);
					Yii::$app->sess->regiswithname('submenu',null);
					Yii::$app->sess->regiswithname('subsubmenu',null);
				}else{
					
					Yii::$app->sess->regiswithname('menu',$menu);
					$datamenu = $menu;
						foreach($menu as $datamenu){
						$paramIdModul[] = $datamenu['id_modul'];
					}
					$query = new Query;
                    $query->select([
                        'b.id_modul_det',
                        'b.id_modul',
                        'b.modul',
                        'b.link',
                        'b.id_modul',
                        'b.parent'
                        ])  
					->from('m_modul AS a')
					->Join(	'RIGHT JOIN', 
						'm_modul_det AS b',
						'a.id_modul = b.id_modul'
					)->where(['b.aktif'=>'1']
					)->andWhere(['IN','b.id_modul',$paramIdModul]);
					$command = $query->createCommand();
					$submenu = $command->queryAll();
					if($submenu == null || $submenu == ""){
                            Yii::$app->sess->regiswithname('submenu',null);
							Yii::$app->sess->regiswithname('subsubmenu',null);
					}else{
						Yii::$app->sess->regiswithname('submenu',$submenu);
						foreach($submenu as $datasubmenu){
							$id_modul_det[] = $datasubmenu['id_modul_det'];
						}
						$query = new Query;
						$query->select([
							'b.id_modul_det',
							'b.modul',
							'b.link',
							])  
							->from('m_modul_det AS a')
							->Join(	'LEFT JOIN', 
								'm_modul_det_det AS b',
								'a.id_modul_det = b.id_modul_det'
							)->where(['b.aktif'=>'1','a.aktif'=>'1']
							)->andWhere(['IN','b.id_modul_det',$id_modul_det]);
							$command = $query->createCommand();
							$subsubmenu = $command->queryAll();
							if($subsubmenu == null || $subsubmenu == ""){
								Yii::$app->sess->regiswithname('subsubmenu',null);
							}else{
								Yii::$app->sess->regiswithname('subsubmenu',$subsubmenu);
							}			   
					}
				}
				return $this->redirect(['dashboard']);
			}else{
				return $this->render('akses',[
					 'listclient' => $listclient,
					 'userdata'=>$Nama_Karyawan
				]);		
			}
		}else{
			throw new \yii\web\NotFoundHttpException("Sorry page not found.");
		}
	}

     public function actionLogout()
    {
        $session = Yii::$app->session;
        $session->open();
        if(Yii::$app->request->post()){
            if($session->get('userdata') != null){
                $session->destroy();
                return $this->redirect(['login']);
            }else{
                throw new \yii\web\NotFoundHttpException("Sorry page not found.");
            }
        }else{
            throw new \yii\web\NotFoundHttpException("Sorry page not found.");
        }
    }

	public function actionDashboard(){
		$userdata = Yii::$app->sess->checkgetsess("userdata");
		$data = Yii::$app->sess->checksession();
		if($data == 1){
			return $this->redirect(['akses']);
		}else if($data == 0){
			return $this->redirect(['login']);
		}
		
		return $this->render('index',[
			'userdata'=>$userdata 
		]);

	}

 public function  actionProsesfuzzy(){
	print_r("daat");
}
}

views/site/akses.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
$js=<<<js
$(document).ready(function() {
  var getUrl = window.location;
  var baseUrl = getUrl .protocol + "//" + getUrl.host + "/" + getUrl.pathname.split('/')[1];
  
  $('select#clientoption').on('change', function() {
    var formData = {
      'datapost':this.value
    };
  
     $.ajax({
      url: baseUrl + '/site/getrole',
      dataType:'json',
      type: 'ajax',
      method:'post',
      async:false,
      data: formData,
      success: function(data){
      
        $('#role').empty();
        $(data['data']).each(function()
        {
          if(this.id_user_client != null && this.id_role != null){
            var option = $('<option>');
            option.attr('value', this.id_role).text(this.role);
            $('#role').append(option);
          }    
        });
      },
      error: function(err){
        console.log(err);
        alert(JSON.stringify(err));
      }
    })
  });   
 
});
js;
$this->registerJs($js);
?>
<div class="login-box">
  <div class="login-logo">
    <a href="#">SRU - TAM</a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">hai <b><?= $userdata;?></b>, Silahkan tentukan user client dan role Anda.</p>

    <?php $form = ActiveForm::begin();?>
      <div class="form-group has-feedback">
		<?= Html::dropDownList('client', 'Client',$listclient,['class'=>'input form-control','id'=>'clientoption','prompt'=>'===PILIH CLIENT===']) ?>
      </div>
      <div class="form-group has-feedback">
		<label>Role</label>
		<select name="role" id="role" class="input form-control">
			<option>== PILIH ROLE ==</option>
		</select>
      </div>
      <div class="row">
        
        <!-- /.col -->
        <div class="col-xs-4">
		<?= Html::submitButton('Login', ['class' => '"btn btn-primary btn-block btn-flat', 'name' => 'login-button']) ?>
        </div>
        <!-- /.col -->
      </div>
    <?php ActiveForm::end(); ?>

    
  </div>
  <!-- /.login-box-body -->
</div>

views/site/datainput_v.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;

$this->params['breadcrumbs'][] = ['label' => 'Data Input', 'url' => Url::base().'/site/datainput'];

?>

<style>
    .jarak {
        margin-top: 1%;
    }

    .jarakmasuk {
        padding-left: 30px;
    }
</style>
<div class="box">
    <div class="box-header">
        <center>
            <h3 class="box-title"><?=$title?></h3>
        </center>
    </div>
    <div class="box-body">
    <div class="row">
    <div class="col-md-12 jarakmasuk">
                <p>Tanggal : <?= $tanggal;?></p>
            </div>    
    
    </div>
    <?php $form = ActiveForm::begin(); ?>
			<div class="row">
				<div class="col-md-4">
					<div class="form-group">
						<label>Tahun:</label>
						<div class="input-group">
							<div class="input-group-addon">
								<i class="fa fa-calendar"></i>
                            </div>
							<input type="date" class="form-control" id="datemask" name="thn" value="<?=$thn?>">
						</div>
						<small>Min:1900, Max:2099</small>
					</div>
				</div>
				<div class="col-md-4">
					<div class="form-group">
						<label>Bulan:</label>
						<div class="input-group">
							<div class="input-group-addon">
								<i class="fa fa-calendar"></i>
							</div>
							<input type="date" class="form-control" id="datemaskbln" name="bln" value="<?=$bln?>">
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
					<div class="form-group">
                    <input type="submit" name="btnfilter" value="Filter" class="btn btn-success"/>
					<a href="<?=Url::base().'/site/prosesfuzzy' ?>"  class="btn btn-info">Proses</a>
					
                    </div>
				</div>
			</div>
		<?php ActiveForm::end(); ?>
        <div class="row">
				<div class="col-md-12">
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal-default">
                    Tambah data
                </button>
				</div>
			</div>
        <div class="row">
            <div class="col-md-12 jarak">
                <table id="example1" class="table table-bordered table-striped table-hover">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Tahun</th>
                            <th>Bulan</th>
                            <th>Kode</th>
                            <th>Edu</th>
                            <th>VI</th>
                            <th>RRS</th>
                            <th>Con</th>
                            <th>CI</th>
                            <th>Acp</th>
                            <th>YS</th>
                            <th>AR</th>
                            <th>Bvr</th>
                            <th>WA</th>
                            <th>VP</th>
                            <th>Dc</th>
                            <th>Atc</th>
                            <th>QW</th>
                            <th>WS</th>
                            <th>RI</th>
                            <th>Ctv</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
						if($model != null){
						$i = 1; 
						foreach($model as $value){
					?>
                        <tr>
                            <td><?= $i;?></td>
                            <td><?= $value["tahun"];?></td>
                            <td><?= $value["bulan"];?></td>
                            <td><?= $value["kode"];?></td>
                            <td><?= $value["edu"];?></td>
                            <td><?= $value["vi"];?></td>
                            <td><?= $value["rrs"];?></td>
                            <td><?= $value["con"];?></td>
                            <td><?= $value["ci"];?></td>
                            <td><?= $value["acp"];?></td>
                            <td><?= $value["ys"];?></td>
                            <td><?= $value["ar"];?></td>
                            <td><?= $value["bvr"];?></td>
                            <td><?= $value["wa"];?></td>
                            <td><?= $value["vp"];?></td>
                            <td><?= $value["dc"];?></td>
                            <td><?= $value["atc"];?></td>
                            <td><?= $value["qw"];?></td>
                            <td><?= $value["ws"];?></td>
                            <td><?= $value["ri"];?></td>
                            <td><?= $value["ctv"];?></td>
                        </tr>
                        <?php
						$i++;
					 	}}
					?>
                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="modal-default">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Default Modal</h4>
              </div>
              <div class="modal-body">
              <?php $form = ActiveForm::begin(); ?>
              <?= $form->field($modeldata, 'tahun')->textInput() ?>
              <?= $form->field($modeldata, 'bulan')->textInput() ?>
              <?= $form->field($modeldata, 'kode')->textInput() ?>
              <?= $form->field($modeldata, 'edu')->textInput() ?>
              <?= $form->field($modeldata, 'vi')->textInput() ?>
              <?= $form->field($modeldata, 'rrs')->textInput() ?>
              <?= $form->field($modeldata, 'con')->textInput() ?>
              <?= $form->field($modeldata, 'ci')->textInput() ?>
              <?= $form->field($modeldata, 'acp')->textInput() ?>
              <?= $form->field($modeldata, 'ys')->textInput() ?>
              <?= $form->field($modeldata, 'ar')->textInput() ?>
              <?= $form->field($modeldata, 'bvr')->textInput() ?>
              <?= $form->field($modeldata, 'wa')->textInput() ?>
              <?= $form->field($modeldata, 'vp')->textInput() ?>
              <?= $form->field($modeldata, 'dc')->textInput() ?>

              <?= $form->field($modeldata, 'atc')->textInput() ?>
              <?= $form->field($modeldata, 'qw')->textInput() ?>
              <?= $form->field($modeldata, 'ws')->textInput() ?>
              <?= $form->field($modeldata, 'ri')->textInput() ?>
              <?= $form->field($modeldata, 'ctv')->textInput() ?>
              <input type="submit" name="simpandata" class="btn btn-primary"/>
              <?php ActiveForm::end(); ?>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                
              </div>
            </div>
            <!-- /.modal-content -->
          </div>
          <!-- /.modal-dialog -->
        </div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<h1>Dashboard</h1>
<div class="row">
	<div class="col-md-4">
		<div class="nav-tabs-custom">
			<!-- Tabs within a box -->
			<ul class="nav nav-tabs pull-right">
				<li class="active"><a href="#revenue-chart" data-toggle="tab">Ranking</a></li>
				<li class="pull-left header"><i class="fa fa-inbox"></i> SPK</li>
			</ul>
			<div class="tab-content no-padding">
				<!-- Morris chart - Sales -->
				<div class="chart tab-pane active" id="revenue-chart" style="position: relative; height: 300px;"></div>
			</div>
		</div>
	</div>
    <div class="col-md-4">
		<div class="nav-tabs-custom">
			<!-- Tabs within a box -->
			<ul class="nav nav-tabs pull-right">
				<li class="active"><a href="#revenue-chart" data-toggle="tab">Ranking</a></li>
				<li class="pull-left header"><i class="fa fa-inbox"></i> SPK</li>
			</ul>
			<div class="tab-content no-padding">
				<!-- Morris chart - Sales -->
				<div class="chart tab-pane active" id="sales-chart" style="position: relative; height: 300px;"></div>
			</div>
		</div>
	</div>
	
    <div class="col-md-4">
		<div class="box box-solid bg-green-gradient">
			<div class="box-header">
				<i class="fa fa-calendar"></i>

				<h3 class="box-title">Calendar</h3>
				<!-- tools box -->
				<div class="pull-right box-tools">
					<!-- button with a dropdown -->
					<button type="button" class="btn btn-success btn-sm" data-widget="collapse"><i
							class="fa fa-minus"></i>
					</button>
					<button type="button" class="btn btn-success btn-sm" data-widget="remove"><i
							class="fa fa-times"></i>
					</button>
				</div>
				<!-- /. tools -->
			</div>
			<!-- /.box-header -->
			<div class="box-body no-padding">
				<!--The calendar -->
				<div id="calendar" style="width: 100%"></div>
			</div>
		</div>
	</div>
</div>

views/site/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

?>
<div class="login-box">
  <div class="login-logo">
    Sistem SPK
  </div>
  <?php if (Yii::$app->session->hasFlash('success')): ?>
    <div class="alert alert-success alert-dismissable">
         <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
         <h4><i class="icon fa fa-check"></i>Saved!</h4>
         <?= Yii::$app->session->getFlash('success') ?>
    </div>
<?php endif; ?>

<?php if (Yii::$app->session->hasFlash('error')): ?>
    <div class="alert alert-danger alert-dismissable">
         <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
         <h4><i class="icon fa fa-exclamation-circle"></i>Failed!</h4>
         <?= Yii::$app->session->getFlash('error') ?>
    </div>
<?php endif; ?>
  <div class="login-box-body">
    <p class="login-box-msg">Sign in to start your session</p>

    <?php $form = ActiveForm::begin();?>
      <div class="form-group has-feedback">
		<?= $form->field($model, 'username')->textInput(['autofocus' => true,'class'=>'form-control','placeholder'=>'Username']) ?>
      </div>
      <div class="form-group has-feedback">
		<?= $form->field($model, 'password')->passwordInput(['class'=>'form-control','placeholder'=>'Password']) ?>
      </div>
      <div class="row">
        
        <!-- /.col -->
        <div class="col-xs-4">
		<?= Html::submitButton('Login', ['class' => '"btn btn-primary btn-block btn-flat', 'name' => 'login-button']) ?>
        </div>
        <!-- /.col -->
      </div>
    <?php ActiveForm::end(); ?>

    
  </div>
  <!-- /.login-box-body -->
</div>